### ISSUE TITLE
As an professor I want to add/remove courses so that professor can be allocated to the courses

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Niraj-Kamdar/question-paper-generator#17]
- [x] add a webpage for admin where he can add course and professor for simplicity assume only one course allocated to only one professor at any time.
- [x] make a database model for course attr would be coursename, courseid, professor and it will get referenced in question db so change appropriately
- [x] do appropriate change in route
- [x] also make a webpage which displays every course and associated prof

**Comment by Leo-0906** [comment]
so we have to make form for adding course and associate professor , right ?

**Comment by Leo-0906** [comment]
its same as adding question right ? can I reference that ?

**Comment by Niraj-Kamdar** [comment]
yes you have to make a form and database model just like question.

**Comment by Niraj-Kamdar** [comment]
mention me in the comment so that i can reach out more easily

**Comment by Leo-0906** [comment]
Got it
