### ISSUE TITLE
Add course user selenium test

### ISSUE THREAD

**Issue by Dgohel11** [Niraj-Kamdar/question-paper-generator#62]
### Describe the test
Add test to add new valid and unique course using selenium webdriver.

### What it covers
It will cover front-end test for the adding of new valid and invalid course.

### Testing

Some tests for the above testcase.

| Description | Input | Output |
| :---------- | :---- | :----- |
|         Add course with valid course name    |  Course name     | Course is added and redirected to add course page      |
| Add course with existed course name | Course name | Error message display |
|Add course with Invalid course name | No Input/Invalid Course name| "This field is required "/Error message display|

**Comment by Niraj-Kamdar** [comment]
well done
