### ISSUE TITLE
List questions selenium test

### ISSUE THREAD

**Issue by sarthak20shah** [Niraj-Kamdar/question-paper-generator#66]
### Describe the test
Add a test to getting list of questions of selected course using selenium webdriver.

### What it covers
It will cover front-end test getting list of questions of selected course.

### Testing

Some tests for the above testcase.

| Description | Input | Output |
| :---------- | :---- | :----- |
|      Show list of subjective questions of course      | click on  any course on courses page      |  list of subjective questions      |
| Show list of mcqs of course      | click on  multiple choice question button in question page     |  list of mcqs      |

**Comment by Niraj-Kamdar** [comment]
Done by @jeel2308 using Oxygen IDE.
