### ISSUE TITLE
Add questions selenium test

### ISSUE THREAD

**Issue by sarthak20shah** [Niraj-Kamdar/question-paper-generator#67]
### Describe the test
Add a test to adding of questions of selected course using selenium webdriver.

### What it covers
It will cover front-end test of adding questions of selected course.

### Testing

Some tests for the above testcase.

| Description | Input | Output |
| :---------- | :---- | :----- |
|  Add question to selected course           |   question , mark, difficulty     |     question is added to list of questions and  question is added to database   |

**Comment by Niraj-Kamdar** [comment]
Done by @jeel2308 using Oxygen IDE.
