### ISSUE TITLE
Update question selenium test

### ISSUE THREAD

**Issue by sarthak20shah** [Niraj-Kamdar/question-paper-generator#68]
### Describe the test
Add a test to updating of questions of selected course using selenium webdriver.

### What it covers
It will cover front-end test of updating questions of selected course.

### Testing

Some tests for the above testcase.

| Description | Input | Output |
| :---------- | :---- | :----- |
|  Update question to selected course           |  question  or mark or difficulty     |   question and it's parameters are updated to list of questions and also updated to database     |

**Comment by Niraj-Kamdar** [comment]
Done by @jeel2308 using Oxygen IDE.
