### ISSUE TITLE
Set IMP flag to question selenium test

### ISSUE THREAD

**Issue by Dgohel11** [Niraj-Kamdar/question-paper-generator#69]
### Describe the test
Add a test to set IMP flag to question using selenium webdriver.

### What it covers
It will cover front-end test for setting IMP flag to the question.

### Testing

Some tests for the above testcase.

| Description | Input | Output |
| :---------- | :---- | :----- |
|    Set IMP flag to  question of selected course         |    Click on flag mark and tickmark on IMP  |        IMP tag on question|

**Comment by Niraj-Kamdar** [comment]
Done by @jeel2308 using Oxygen IDE.
